src/main/java/org/apache/cassandra/service/StorageService.java
Column family is not being passed, so the requests fail to reach the
correct endpoint.
Signed-off-by: Glauber Costa <glauber@scylladb.com>
=> fix auto_compaction request strings

src/main/java/org/apache/cassandra/db/ColumnFamilyStore.java, src/main/java/org/apache/cassandra/db/ColumnFamilyStoreMBean.java
Cassandra 3.0 version of the JMX added a parameter that allows accepting
the parameter as hex.
This breaks the current implementation with a NoSuchMethodException.
This patch adds the missing implementation.
For a full support, a follow up patch in Scylla is needed, but for the
current functionality it would work.
After this patch usage example:
nodetool getsstables keyspace1 standard1 39303138374b4d343830
Signed-off-by: Amnon Heiman <amnon@scylladb.com>
=> ColumnFamilyStore: Mbean API support the hex format param

src/main/java/org/apache/cassandra/metrics/CompactionMetrics.java
The PendingTasksByTableName metric should use the pending_tasks_by_table
API to get the real value of the pending compaction.
Fixes #74
Signed-off-by: Amnon Heiman <amnon@scylladb.com>
=> CompactionMetrics: use the pending compaction API

scylla-apiclient/pom.xml, scylla-apiclient/src/main/java/com/scylladb/jmx/api/APIClient.java, src/main/java/com/scylladb/jmx/utils/DateXmlAdapter.java, src/main/java/org/apache/cassandra/service/PerTableSSTableInfo.java, src/main/java/org/apache/cassandra/service/SSTableInfo.java, src/main/java/org/apache/cassandra/service/StorageService.java, src/main/java/org/apache/cassandra/service/StorageServiceMBean.java
Fixes #76 
Implements JMX level call for "sstable_info" REST api command.
Requires seastar patch:
json: Make date formatter use RFC8601/RFC3339 format
Requires scylla patch set "Implement `sstable_info` API command (info on sstables)"
Forwards call to REST sstable_info and packs the data
into CompositeData for JMX consumption.
=> Implement sstable_info command

dist/debian/build_deb.sh
Takuya had untemplataize scylla-jmx.service in commit e8355087ead4bded8f31ee8746f36dc097d5f7a1
But the build_deb.sh still tries to generate service file from a deleted
mustache template file -- scylla-jmx.spec.mustache. It wrongly redirects
a path to service file, then scylla-jmx would fail to start.
Fixes #80
Signed-off-by: Amos Kong <amos@scylladb.com>
/CC @syuu1228
=> build_deb.sh: don't generate scylla-jmx.service from mustache template

dist/common/systemd/scylla-jmx.service
Scylla now supports server-defined systemd slices that are used to provide
isolation between components.
This patch adds scylla-jmx to the helper slice. This will guarantee that
scylla-jmx does not use too much resources, influencing the server performance.
Signed-off-by: Glauber Costa <glauber@scylladb.com>
=> run scylla-jmx in a systemd slice

.github/CODEOWNERS
Add myself as a "code owner" so that I am assigned a review
automatically:
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
I also wanted to add Amnon and Calle, but apparently you need to have
write permissions in order to be a code owner.
The purpose of this automation is to ensure Scylla JMX pull requests
show up in my github.com/pulls page. Thanks Maciej Zimnoch for the tip!
=> Add Pekka as a "code owner" on GitHub

dist/redhat/scylla-jmx.spec.mustache
Since %systemd_post does not call systemctl --daemon-reload, we need to call it
manually to apply changes.
Fixes #90
=> dist/redhat: call systemctl --daemon-reload when upgraded

dist/redhat/scylla-jmx.spec.mustache, install.sh
On the commit 4c8660d, we dropped /usr/lib/scylla/jmx since it likely no user
script invoke scripts under the directory.
However, we found there are possibility scylla-jmx.service tries to load .jar
file from /usr/lib/scylla/jmx, when user upgraded from older version of scylla.
Because /etc/sysconfig/scylla-jmx is marked as 'noreplace' on our rpm,
yum upgrade may keep old sysconfig file when it modified by user, that may
causes to load .jar from /usr/lib/scylla/jmx since we specify the path in the
sysconfig file.
To avoid the issue it's better to have symlinks on /usr/lib/scylla/jmx for
safety.
See #90
=> dist: add /usr/lib/scylla/jmx for compatibility

dist/redhat/build_rpm.sh, dist/redhat/scylla-jmx.spec.mustache, dist/redhat/systemd.inc
Fedora 31 version of systemd macros does not work correctly on CentOS7,
since CentOS7 does not support "file trigger" feature.
Even after 05d4378, scriptlets on old scylla .rpm and new scylla .rpm is
not completely same.
To fix the issue we need to override macros with CentOS7 version.
Fixes #94
=> dist/redhat: override systemd macros to CentOS7 version

dist/common/sysconfig/scylla-jmx
Add SCYLLA_JMX_JVM_OPTS on sysconfig to specify JVM options.
fixes #58
=> dist: allow specify JVM options from sysconfig

dist/redhat/scylla-jmx.spec.mustache, reloc/build_deb.sh, reloc/build_rpm.sh, scripts/create-relocatable-package.py
To make unified relocatable package easily, we may want to merge tarballs to single tarball like this:
zcat .tar.gz | gzip -c > scylla-unified.tar.xz
But it's not possible with current relocatable package format, since there are multiple files conflicts, install.sh, SCYLLA--FILE, dist/, README.md, etc..
To support this, we need to archive everything in the directory when building relocatable package.
See: scylladb/scylla#6315
=> reloc-pkg: move all files under project name directory

src/main/java/org/apache/cassandra/db/ColumnFamilyStore.java, src/main/java/org/apache/cassandra/service/StorageService.java
align API to the recent changes at https://github.com/scylladb/scylla/pull/6176
don't wrap API exceptions into IOException for enableAutoCompaction
related a bit https://github.com/scylladb/scylla-tools-java/pull/165
=> fix is auto compaction disabled

src/main/java/org/apache/cassandra/service/StorageService.java, src/main/java/org/apache/cassandra/service/StorageServiceMBean.java
The scrub command was not supported from node_tool, but now when we want
to enable it the current API is not compatible with the 3.11 MBean
definition.
This patch adds the definition to the MBean and the implementation to
StorageService.
It also addresses two problems with the old scrub implementation, just
in case someone will use them.
1. Implementation didn't pass the parameters to the API.
2. A stub implementation called itself instead of calling an actual
implementation.
This patch will enable to test the command from nodetool additional
changes may come on top of it if more command line options will be
supported.
Relates to scylladb/scylla#6072
Signed-off-by: Amnon Heiman <amnon@scylladb.com>
=> StorageService: Add the scrub 3.11 command implementation

dist/debian/debian/rules, dist/debian/debian/scylla-jmx.install
Installing *.service by install.sh script causes the error on installing .deb
package, use debian/*.service instead.
Fixes scylladb/scylla#6010
Related scylladb/scylla#5640
Related https://github.com/scylladb/scylla/commit/29285b28e2de2f07593a65a5f03977da440b2e42
=> dist/debian: don't install systemd unit by install.sh, use debian/*.service

dist/debian/debian/rules, dist/redhat/scylla-jmx.spec
354df10 mistakenly does not contain dist/redhat & dist/debian change,
add --package option to them.
=> dist: add --packaging for .rpm/.deb build

dist/debian/build_deb.sh
Same as scylladb/scylla#6752,
we currently does not able to apply version number fixup for .orig.tar.gz file,
even we applied correct fixup on debian/changelog, becuase it just reading
SCYLLA-VERSION-FILE.
We should parse debian/{changelog,control} instead.
Fixes #120
=> dist/debian: apply generated package version for .orig.tar.gz file

dist/common/systemd/scylla-jmx.service
Currently scylla-jmx.service's PWD is "/", we get following error when
JVM trying to write heap dump on current directory:
Aug 17 05:52:15 localhost.localdomain scylla-jmx[3469]: Starting the JMX server
Aug 17 05:52:16 localhost.localdomain scylla-jmx[3469]: java.lang.OutOfMemoryError: Java heap space
Aug 17 05:52:16 localhost.localdomain scylla-jmx[3469]: Dumping heap to java_pid3469.hprof ...
Aug 17 05:52:16 localhost.localdomain scylla-jmx[3469]: Unable to create java_pid3469.hprof: Permission denied
To fix this, we need to specify WorkingDirectory on systemd unit.
See scylladb/scylla-enterprise#1469
=> dist/common/systemd: set WorkingDirectory to get heap dump correctly

install.sh
Currently after offline installation, the scylla-jmx fails to be started.
This patch fixed the problem.
Fixes: https://github.com/scylladb/scylla/issues/7098 by [PATCH] install.sh: check both openjdk-8 and openjdk-11
Fixes: https://github.com/scylladb/scylla-jmx/issues/129 by [PATCH] nonroot.conf: set WorkingDirectory to empty
=> fix offline installation

src/main/java/com/scylladb/jmx/metrics/APIMBean.java, src/main/java/com/scylladb/jmx/metrics/RegistrationChecker.java, src/main/java/com/scylladb/jmx/metrics/RegistrationMode.java, src/main/java/com/scylladb/jmx/utils/APIMBeanServer.java, src/main/java/org/apache/cassandra/db/ColumnFamilyStore.java, src/main/java/org/apache/cassandra/metrics/StreamingMetrics.java, src/main/java/org/apache/cassandra/metrics/TableMetrics.java
Fixes #133
Fixes #134 
Refs #135
Makes CF mbean refresh code synchronized and tries to remove reductant calls if we contend. 
Adds background reaping of dead objects to reduce memory load in (test) scenarios where we manage
to refresh to add, but not cause removal (i.e. no wildcard queries). 
TableMetricsObjectName serialization is fixed in the series because without it we see loads of 
exceptions when refreshing the mbean set.
=> JMX footprint work

SCYLLA-VERSION-GEN, reloc/build_reloc.sh
Instead of using the baked-in values from SCYLLA-VERSION-GEN,
allow passing an override. This will be used by the supermodule
to have an identical product-version-release (especially release,
which contains the git hash) across all packages.
=> build: support passing product-version-release as a parameter

install.sh
On some environment, systemctl enable <service> fails when we use symlink.
So just directly copy systemd units to ~/.config/systemd/user, instead of
creating symlink.
See scylladb/scylla#7288
=> install.sh: stop using symlinks for systemd units on nonroot mode

dist/debian/debian_files_gen.py
shutil.rmtree(ignore_errors=True) was for ignores error when directory not exist,
but it also ignores permission error, so we shouldn't use that.
Run os.path.exists() before shutil.rmtree() instead.
See scylladb/scylla#7337
=> dist/debian/debian_files_gen.py: don't ignore permission error on shutil.rmtree()

src/main/java/org/apache/cassandra/db/ColumnFamilyStore.java
Right now, in the finishLocalSampling method of the ColumnFamilyStore
we return the size of the list of returned partitions. Instead, we should
be propagating the actual cardinality of the sampled set.
Let's just read the read_cardinality and write_cardinality properties
of the scylla's REST API response.
Fixes #148
=> column_family: Return proper cardinality for toppartitions requests

install.sh
In commit 6311525, we set an empty value to WorkDirectory for nonroot.conf
of scylla-jmx.service. It works with ubuntu16, debian9, debian 10. But it
doesn't work with ubuntu 18.
This patch changed the WorkingDirectory of nonroot offline install to
default install directory (/home/scylla-test/scylladb).
Fixes: #151
Signed-off-by: Amos Kong <amos@scylladb.com>
=> install.sh: set a valid WorkingDirectory for nonroot offline install

dist/redhat/scylla-jmx.spec
This is v2 of #95, since it's dequeued.
----
Fedora version of systemd macros does not work correctly on CentOS7,
since CentOS7 does not support "file trigger" feature.
Even after 05d4378, scriptlets on old scylla .rpm and new scylla .rpm is
not completely same.
To fix the issue we need to stop using systemd macros, call systemctl
directly.
Fixes #94
=> dist/redhat: stop using systemd macros, call systemctl directly

src/main/java/org/apache/cassandra/db/compaction/CompactionManager.java
This patch adds the compaction id in getCompactions if it returns by the
API, if it's not the current behaviour will be used and it will return none.
After this patch a call to nodetool compactionstats -H
Will return:
id                                   compaction type keyspace  table     completed total unit progress
c942bd30-7a62-11eb-84bc-576502584f9a COMPACTION      keyspace1 standard1 1062      8576  keys 12.38%
c9429620-7a62-11eb-8afb-576402584f9a COMPACTION      keyspace1 standard1 972       8448  keys 11.51%
Active compaction remaining time :   0h00m00s
Fixes scylladb/scylla#7927
Signed-off-by: Amnon Heiman <amnon@scylladb.com>
=> CompactionManager: add the compaction id when available

src/main/java/com/scylladb/jmx/utils/APIBuilder.java
This pull request reverts the commit c2fc96b ("APIBuilder: Remove
RW-lock in JMX server repository wrapper") and fixes a missing unlock
from APIBuilder.remove().
=> Fix locking in APIBuilder.remove()

dist/redhat/scylla-jmx.spec
CentOS/RHEL and SLES has differnt package name of opejdk, use common
name of JRE.
Note that using common name of Java package is also useful when user want to
use differnt implementation of JRE for Scylla.
Also, disable AutoReqProv which is mistakenly enabled but required for
cross build rpm.
=> dist/redhat: add support SLES

install.sh
On older distribution such as CentOS7, it does not support systemd user mode.
On such distribution nonroot mode does not work, show warning message and
skip running systemctl --user.
See scylladb/scylla#7071
=> install.sh: show warning nonroot mode when systemd does not support user mode

src/main/java/org/apache/cassandra/service/StorageService.java, src/main/java/org/apache/cassandra/service/StorageServiceMBean.java
As part of making the toppartitions API more generic
(i.e. being able to consider multiple tables
and keyspaces specified by the user) this commit adds
a JMX endpoint to call the generic Scylla REST API
introduced in [#7864](https://github.com/scylladb/scylla/pull/7864). It has been put inside
storage_service as being now able to query more than
one column family makes it no longer suitable for the
'column_family' group.
Fixes #4520
=> storage_service: Add a generic toppartitions endpoint

src/main/java/org/apache/cassandra/service/StorageService.java, src/main/java/org/apache/cassandra/service/StorageServiceMBean.java
This information is translated to {"load_and_stream", "true"} entry in the
POST request to Scylla's HTTP API at `storage_service/sstables/{keyspace}`
endpoint.
More about this feature: scylladb/scylla#7846
Mutually bonded change: scylladb/scylla-tools-java#273
Refs scylladb/scylla-tools-java#253.
=> Support `--load-and-stream` option from `nodetool refresh`

scylla-apiclient/pom.xml
Update jackson dependency to a newer version without any known
vulnerabilities. I have checked changelogs of all versions between
2.12.1 and 2.12.6.1, and none of the changes were potentially
problematic (consistent of minor fixes, etc).
2.12.6.1 version of jackson-databind is compatible with 2.12.6 versions
of other jackson packages.
=> Update jackson dependency

install.sh, scripts/create-relocatable-package.py
Since we fail to write files to $USER/.config on Jenkins jobs, we need
an option to skip installing systemd units.
Let's add --without-systemd to do that.
See scylladb/scylla-dtest#2819
----
This is jmx part of scylladb/scylla#11345
=> install.sh: add --without-systemd option

install-dependencies.sh, install.sh
in hope to alleviate the pain of #194, this series enables us to 
- install OpenJDK 11 instead of OpenJDK 8 in `install-dependencies.sh`
- add symbolic link to java provided by OpenJDK 11 if it is available, and use the one from OpenJDK 8 as a fallback
Refs #194
=> use OpenJDK 11 instead of OpenJDK 8

scripts/select-java
both `dpkg -L .. | grep '/java$'` and `rpm -ql .. | grep '/java$`
can return multiple matches. and before this change, we just exec
the returned string even if it could include multiple paths.
after this change, when selecting java for debian and ubuntu,
use the path of `/usr/lib/jvm/java-11-openjdk-${arch}/bin/java` instead.
when selecting java for fedora and centos, we just return the first
path of `/usr/lib/jvm/jre-${version}-openjdk/bin/java` which exists.
this should address the failure like
```
Error: Could not find or load main class .usr.lib.jvm.java-8-openjdk-arm64.bin.java
```
when launching scylla-jmx as a service on a ubuntu box where
openjdk-8-jre-headless is installed, because:
```console
$ dpkg -L openjdk-8-jre-headless | grep '/java$' …
```
=> select-java: avoid exec multiple paths 

dist/debian/control.template
this change mirrors https://github.com/scylladb/scylla-jmx/commit/f89670dfd80ed04860e1098f0fc6ef114793f31b,
since the oldest supported debian and its derivative are debian 10 and
ubuntu 18.04, both of which ship openjdk-11-jre-headless. and
oracle provides oracle-java11-set-default for them. so it's safe
to drop the optional dependencies on openjdk-8 and orcale-java8.
this would ensure that the scylla-jmx deb package's access to
jdk-11.
Fixes https://github.com/scylladb/scylla-jmx/issues/194
=> dist/debian: drop dependencies on jdk-8

dist/debian/control.template
=> dist/debian: split Depends into multiple lines

install.sh
in 96adf0ef51ad49b6abb98867f73cf69705f5f3e3, we started using `select-java` for selecting the JRE for running scylla-jmx, but it failed to reference `select-java` with the correct path. as in the unified reloc package, `select-java` is located at `scylla-jmx/select-java`, `install.sh` is located under the same directory. so we should use `./select-java` here.
also, we should error out if the expected JDK is not found. this is the behavior before 96adf0ef51ad49b6abb98867f73cf69705f5f3e3
=> install.sh: bail out if jdk is not available

install-dependencies.sh
Especially for Java, we really do not need the tens of packages and MBs it adds, just because Java apps can be built and use sound and graphics and whatnot.
(Identical PR was sent earlier to scylla-tools-java repo)
=> install-dependencies.sh: do not install weak dependencies

README.md
Before the change, the character after `$` was a `0xA0` (NBSP) character, which is rendered incorrectly by some text editors. Replace it with a regular space character.
=> README: replace 0xA0 (NBSP) character with space

scylla-apiclient/pom.xml
This PR updates several dependencies which were flagged by security scanners. In particular:
1. Jackson dependencies: `com.fasterxml.jackson.core:jackson-databind` used in the project was
vulnerable to CVE-2022-42003 and CVE-2022-42004 ("HIGH" severity)
2. snakeyaml dependency: `org.yaml:snakeyaml` used in the project was vulnerable to CVE-2022-1471 ("CRITICAL" severity), CVE-2022-25857, CVE-2022-38749, CVE-2022-38750, CVE-2022-38751, CVE-2022-38752, CVE-2022-41854
3. Guava dependency: `com.google.guava` used in the project was vulnerable to CVE-2023-2976 ("HIGH" severity) and CVE-2020-8908
Please note that at the moment there is no reason to believe that those dependency issues could have affected scylla-jmx itself.
This version of JMX was successfully tested through ScyllaDB CI: …
=> scylla-apiclient: update several Java dependencies

src/main/java/com/scylladb/jmx/utils/APIBuilder.java, src/main/java/org/apache/cassandra/db/ColumnFamilyStore.java
As noted in #226, nodetool breaks if a table name contains the colon character. This normally can't happen - CQL table names can only contain alphanumerics and underscores, and the DynamoDB API adds also dashes and dots - but neither allows a colon. But unfortunately, when Alternator has a secondary index (GSI or LSI), the name of the view _does_ get a colon (it looks like "tablename:viewname"). And this confuses JMX, which addresses objects using MBean names (see https://docs.oracle.com/javase/8/docs/api/javax/management/ObjectName.html), where a name that contains a colon needs to be quoted.
This small series fixes two things: First, some internal list of ObjectName objects needs to quote the names it holds to allow the colon character. Second, we should allow the external client - …
=> Fix handling of table names with colon characters

install.sh
On scylla main repo, we had problem that install.sh install files with incorrect permission on strict umask:
- scylladb/scylladb#10752
- scylladb/scylladb#14383
To fix this, we need to "chmod" on newly created files.
Also, we need to run /usr/bin/install with "-Z" to avoid SELinux permission issue:
- scylladb/scylladb#8589
=> install.sh: fix incorrect permission on strict umask
